### PR TITLE
chore(updatecli) Keep track of Jenkins agent version

### PR DESCRIPTION
**Pull request by smerle33**
adding the updatecli versioning with an ARG and updating the CST file appropriately. 
@dduportal  I wonder if it need a check on the existence of the docker image in the hub somewhere within the process.

fix : #42

### CODE REVIEW

**Comment by dduportal** [comment]
> adding the updatecli versioning with an ARG and updating the CST file appropriately. @dduportal I wonder if it need a check on the existence of the docker image in the hub somewhere within the process.

Good point, this is correct (as the source is a GitHub release)!

**Comment by smerle33** [comment]
> 

```
checkDockerImagePublished:
    name: "Is latest dockerfile docker-inbound-agent image published?"
    kind: dockerImage
    sourceID: lastVersion
    spec:
      image: "jenkinsci/docker-inbound-agent" #jenkinsciinfra/inbound-agent-docker how can I make sure of the hub.docker.com name ?

```
@dduportal how can I make sure of the hub.docker.com name ? sounds more like jenkinsciinfra/inbound-agent-docker but I want certainties.

**Comment by lemeurherve** [comment]
The name is defined in the docker-inbound-agent pipeline: https://github.com/jenkins-infra/docker-inbound-agents/blob/main/Jenkinsfile_k8s#L6

**Comment by dduportal** [comment]
Let's consider the "target" of the manifest: it's changing the tag, in the `Dockerfile`, of the Docker image used as "FROM" instruction.

So the condition should check that this image (with the new tag from the source) exists.

Hence you can be sure that the value would be from https://github.com/jenkins-infra/docker-helmfile/pull/59/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R2

**Comment by smerle33** [comment]
> Let's consider the "target" of the manifest: it's changing the tag, in the `Dockerfile`, of the Docker image used as "FROM" instruction.
> 
> So the condition should check that this image (with the new tag from the source) exists.
> 
> Hence you can be sure that the value would be from https://github.com/jenkins-infra/docker-helmfile/pull/59/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R2

I think I got it right, just need to remove the comments on scmID

**Review by dduportal — APPROVED** [review]
LGTM! Great work.

The build is not failing because of this PR, but because of:
- https://github.com/updatecli/updatecli/issues/465 is not implemented yet (e.g. no "local mode")
- There is a go panic because the updatecli used on the pipeline library is still 0.18.3 (https://infra.ci.jenkins.io/blue/organizations/jenkins/Docker%20Builds%2Fdocker-helmfile/detail/PR-59/8/pipeline#step-34-log-5) while fixed in [0.19.1](https://github.com/updatecli/updatecli/releases/tag/v0.19.1)

Mergin with my admin right because it's great work and should work :)

**Pull request merged**
